name: kenji_player_example
description: A new Flutter project.
version: 1.0.0+1


environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=3.16.2"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  video_player: ^2.8.6
  dio: ^5.9.0
  kenji_player:
    path: "../"

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
