name: kenji_player
description: Kenji Video Player is a video player for flutter. The video_player plugin gives low level access for the video playback.
homepage: https://github.com/kenji-07/kenji_player
repository: https://github.com/kenji-07/kenji_player
version: 1.0.6

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.5"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  video_player: ^2.10.0
  wakelock_plus: ^1.4.0
  volume_controller: ^3.4.0
  screen_brightness: ^2.1.7
  battery_plus: ^7.0.0
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  animate_do: ^4.2.0
  url_launcher: ^6.3.2
  get_storage: ^2.1.1
  phosphor_flutter: ^2.1.0
  interactive_media_ads: ^0.3.0+2
  pointycastle: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


topics:
  - video-player
